version: '2'

services:
  elasticsearch:
    image: elasticsearch:5.1
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:5.1
    links:
      - elasticsearch
    ports:
      - 5601:5601
  logstash:
    image: logstash:5.1
    command: -f /etc/logstash/conf.d
    volumes:
      - ./logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
    links:
      - elasticsearch
    ports:
      - 5000:5000
